
version: 3.0.3

name: Center for Imaging Medicine at Dartmouth

privacy_link: https://dartmouth.edu/privacy

contact_page: https://cim.dartmouth.edu/contact-us.html

update_link: https://cim.dartmouth.edu/update

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"