---
title: Cim
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
version: 3.0.3
name: Center for Imaging Medicine at Dartmouth
privacy_link: http://dartmouth.edu/privacy
contact_page: http://cim.dartmouth.edu/contact-us.html
update_link: https://cim.dartmouth.edu/update
